[package]
name = "jsonata-rs"
version = "0.1.0"
authors = ["David Mikulis <davidmikulis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.0"
serde_json = "1.0.64"
